// dashboardData.js - Static data for energy dashboard

export const performanceMetrics = {
  weeklyGeneration: [
    { day: 'Mon', solar: 420, wind: 380, hydro: 340 },
    { day: 'Tue', solar: 450, wind: 400, hydro: 360 },
    { day: 'Wed', solar: 480, wind: 420, hydro: 350 },
    { day: 'Thu', solar: 460, wind: 390, hydro: 370 },
    { day: 'Fri', solar: 440, wind: 380, hydro: 345 },
    { day: 'Sat', solar: 410, wind: 360, hydro: 330 },
    { day: 'Sun', solar: 390, wind: 340, hydro: 320 }
  ],
  efficiency: {
    solar: 92,
    wind: 88,
    hydro: 95,
    biomass: 74,
    geothermal: 85
  }
};

export const systemHealth = {
  uptime: 99.98,
  responseTime: 89,
  errorRate: 0.02,
  cpuUsage: 42,
  memoryUsage: 67,
  diskSpace: 35
};

export const maintenanceSchedule = [
  {
    id: 1,
    title: 'Solar Panel Cleaning',
    date: '2025-03-20T08:00:00',
    duration: '3 days',
    status: 'scheduled',
    description: 'Regular cleaning and inspection of solar panels'
  },
  {
    id: 2,
    title: 'Wind Turbine Maintenance',
    date: '2025-03-22T09:00:00',
    duration: '2 days',
    status: 'scheduled',
    description: 'Preventative maintenance for wind turbines'
  },
  {
    id: 3,
    title: 'Hydro Generator Inspection',
    date: '2025-03-19T10:00:00',
    duration: '1 day',
    status: 'completed',
    description: 'Routine inspection of hydro generators'
  }
];

export const quickActions = [
  {
    id: 'generate-report',
    title: 'Generate Report',
    icon: 'file-text',
    path: '/energy/reports/generate'
  },
  {
    id: 'view-forecast',
    title: 'View Forecast',
    icon: 'trending-up',
    path: '/energy/forecast'
  },
  {
    id: 'system-settings',
    title: 'System Settings',
    icon: 'settings',
    path: '/energy/settings'
  },
  {
    id: 'export-data',
    title: 'Export Data',
    icon: 'download',
    path: '/energy/export'
  }
];

export const energySourceDetails = {
  solar: {
    name: 'Solar Energy',
    description: 'Energy generated from solar panels converting sunlight into electricity',
    advantages: [
      'Renewable and sustainable',
      'Low operating costs',
      'Zero emissions during operation',
      'Modular and scalable'
    ],
    disadvantages: [
      'Weather dependent',
      'Requires large installation area',
      'Intermittent generation',
      'Storage challenges'
    ],
    efficiency: '15-22%',
    lifespan: '25-30 years'
  },
  wind: {
    name: 'Wind Energy',
    description: 'Energy generated by converting wind into electricity using turbines',
    advantages: [
      'Renewable and sustainable',
      'No water usage for electricity generation',
      'Low operating costs',
      'Can be deployed offshore'
    ],
    disadvantages: [
      'Wind speed variability',
      'Visual and noise impact',
      'Potential wildlife impact',
      'High initial investment'
    ],
    efficiency: '35-45%',
    lifespan: '20-25 years'
  },
  hydro: {
    name: 'Hydropower',
    description: 'Energy generated from flowing water driving turbines',
    advantages: [
      'Highly reliable base load power',
      'Very high efficiency',
      'Long operational life',
      'Low greenhouse gas emissions'
    ],
    disadvantages: [
      'Environmental impact on river ecosystems',
      'High upfront construction costs',
      'Dependent on water availability',
      'Potential for displacement of communities'
    ],
    efficiency: '85-95%',
    lifespan: '50-100 years'
  },
  biomass: {
    name: 'Biomass Energy',
    description: 'Energy generated from organic materials such as plants and waste',
    advantages: [
      'Can utilize waste materials',
      'Carbon neutral when managed properly',
      'Reliable baseload power',
      'Reduces landfill waste'
    ],
    disadvantages: [
      'Lower energy density than fossil fuels',
      'Emissions during combustion',
      'Land use competition with food crops',
      'Transportation logistics'
    ],
    efficiency: '20-40%',
    lifespan: '30-40 years'
  },
  geothermal: {
    name: 'Geothermal Energy',
    description: 'Energy generated from heat within the Earth',
    advantages: [
      'Consistent baseload power',
      'Very low emissions',
      'Small land footprint',
      'Independent of weather conditions'
    ],
    disadvantages: [
      'Location specific availability',
      'High upfront drilling costs',
      'Potential for seismic activity',
      'Mineral scaling and corrosion'
    ],
    efficiency: '10-20%',
    lifespan: '30-50 years'
  }
};

export const regionInfo = {
  'Northern': {
    population: 5.2,
    area: 45000,
    mainSources: ['Wind', 'Hydro'],
    peakDemand: 1200,
    growthRate: 3.2
  },
  'Eastern': {
    population: 4.8,
    area: 38000,
    mainSources: ['Solar', 'Biomass'],
    peakDemand: 980,
    growthRate: 2.7
  },
  'Southern': {
    population: 3.6,
    area: 30000,
    mainSources: ['Solar', 'Geothermal'],
    peakDemand: 840,
    growthRate: 1.9
  },
  'Western': {
    population: 4.1,
    area: 35000,
    mainSources: ['Wind', 'Solar'],
    peakDemand: 920,
    growthRate: 2.5
  },
  'Central': {
    population: 8.3,
    area: 25000,
    mainSources: ['Solar', 'Biomass', 'Hydro'],
    peakDemand: 1500,
    growthRate: 3.8
  }
};

export default {
  performanceMetrics,
  systemHealth,
  maintenanceSchedule,
  quickActions,
  energySourceDetails,
  regionInfo
};