// peerToPeerDummyData.js
// Comprehensive dummy data for Peer-to-Peer Admin prototype

// Sample data for multiple years
export const peerToPeerDummyData = [
    {
      id: "67c698036bbacc4b3abdd2a9",
      Year: 2022,
      "Cebu Total Power Generation (GWh)": "6,145",
      "Cebu Total Non-Renewable Energy (GWh)": "6,144.81",
      "Cebu Total Renewable Energy (GWh)": 85,
      "Cebu Geothermal (GWh)": 0,
      "Cebu Hydro (GWh)": 2,
      "Cebu Biomass (GWh)": 0,
      "Cebu Solar (GWh)": 83,
      "Cebu Wind (GWh)": 0,
      "Negros Total Power Generation (GWh)": "2,638",
      "Negros Total Non-Renewable Energy (GWh)": 28,
      "Negros Total Renewable Energy (GWh)": "2,610",
      "Negros Geothermal (GWh)": "1,683",
      "Negros Hydro (GWh)": 7,
      "Negros Biomass (GWh)": 468,
      "Negros Solar (GWh)": 452,
      "Negros Wind (GWh)": 0,
      "Panay Total Power Generation (GWh)": "3,105",
      "Panay Total Non-Renewable Energy (GWh)": "1,589.83",
      "Panay Total Renewable Energy (GWh)": 246,
      "Panay Geothermal (GWh)": 0,
      "Panay Hydro (GWh)": 21,
      "Panay Biomass (GWh)": 49,
      "Panay Solar (GWh)": 0,
      "Panay Wind (GWh)": 176,
      "Leyte-Samar Total Power Generation (GWh)": "4,253",
      "Leyte-Samar Total Non-Renewable (GWh)": 44,
      "Leyte-Samar Total Renewable (GWh)": "4,209",
      "Leyte-Samar Geothermal (GWh)": "4,130",
      "Leyte-Samar Hydro (GWh)": 0,
      "Leyte-Samar Biomass (GWh)": 0,
      "Leyte-Samar Solar (GWh)": 79,
      "Leyte-Samar Wind (GWh)": 0,
      "Bohol Total Power Generation (GWh)": 81,
      "Bohol Total Non-Renewable (GWh)": 72,
      "Bohol Total Renewable (GWh)": 9,
      "Bohol Geothermal (GWh)": 0,
      "Bohol Hydro (GWh)": 9,
      "Bohol Biomass (GWh)": 0,
      "Bohol Solar (GWh)": 0,
      "Bohol Wind (GWh)": 0,
      "Visayas Total Power Generation (GWh)": "16,327",
      "Visayas Total Power Consumption (GWh)": "15,175",
      "Solar Cost (PHP/W)": 72,
      "MERALCO Rate (PHP/kWh)": 11
    },
    {
      id: "67c698036bbacc4b3abdd2b1",
      Year: 2021,
      "Cebu Total Power Generation (GWh)": "5,890",
      "Cebu Total Non-Renewable Energy (GWh)": "5,832",
      "Cebu Total Renewable Energy (GWh)": 58,
      "Cebu Geothermal (GWh)": 0,
      "Cebu Hydro (GWh)": 2,
      "Cebu Biomass (GWh)": 0,
      "Cebu Solar (GWh)": 56,
      "Cebu Wind (GWh)": 0,
      "Negros Total Power Generation (GWh)": "2,520",
      "Negros Total Non-Renewable Energy (GWh)": 38,
      "Negros Total Renewable Energy (GWh)": "2,482",
      "Negros Geothermal (GWh)": "1,652",
      "Negros Hydro (GWh)": 7,
      "Negros Biomass (GWh)": 445,
      "Negros Solar (GWh)": 378,
      "Negros Wind (GWh)": 0,
      "Panay Total Power Generation (GWh)": "2,980",
      "Panay Total Non-Renewable Energy (GWh)": "1,792",
      "Panay Total Renewable Energy (GWh)": 188,
      "Panay Geothermal (GWh)": 0,
      "Panay Hydro (GWh)": 21,
      "Panay Biomass (GWh)": 35,
      "Panay Solar (GWh)": 0,
      "Panay Wind (GWh)": 132,
      "Leyte-Samar Total Power Generation (GWh)": "4,100",
      "Leyte-Samar Total Non-Renewable (GWh)": 50,
      "Leyte-Samar Total Renewable (GWh)": "4,050",
      "Leyte-Samar Geothermal (GWh)": "4,000",
      "Leyte-Samar Hydro (GWh)": 0,
      "Leyte-Samar Biomass (GWh)": 0,
      "Leyte-Samar Solar (GWh)": 50,
      "Leyte-Samar Wind (GWh)": 0,
      "Bohol Total Power Generation (GWh)": 75,
      "Bohol Total Non-Renewable (GWh)": 68,
      "Bohol Total Renewable (GWh)": 7,
      "Bohol Geothermal (GWh)": 0,
      "Bohol Hydro (GWh)": 7,
      "Bohol Biomass (GWh)": 0,
      "Bohol Solar (GWh)": 0,
      "Bohol Wind (GWh)": 0,
      "Visayas Total Power Generation (GWh)": "15,565",
      "Visayas Total Power Consumption (GWh)": "14,780",
      "Solar Cost (PHP/W)": 78,
      "MERALCO Rate (PHP/kWh)": 10.5
    },
    {
      id: "67c698036bbacc4b3abdd2c2",
      Year: 2020,
      "Cebu Total Power Generation (GWh)": "5,500",
      "Cebu Total Non-Renewable Energy (GWh)": "5,470",
      "Cebu Total Renewable Energy (GWh)": 30,
      "Cebu Geothermal (GWh)": 0,
      "Cebu Hydro (GWh)": 2,
      "Cebu Biomass (GWh)": 0,
      "Cebu Solar (GWh)": 28,
      "Cebu Wind (GWh)": 0,
      "Negros Total Power Generation (GWh)": "2,310",
      "Negros Total Non-Renewable Energy (GWh)": 45,
      "Negros Total Renewable Energy (GWh)": "2,265",
      "Negros Geothermal (GWh)": "1,600",
      "Negros Hydro (GWh)": 7,
      "Negros Biomass (GWh)": 420,
      "Negros Solar (GWh)": 238,
      "Negros Wind (GWh)": 0,
      "Panay Total Power Generation (GWh)": "2,780",
      "Panay Total Non-Renewable Energy (GWh)": "1,680",
      "Panay Total Renewable Energy (GWh)": 100,
      "Panay Geothermal (GWh)": 0,
      "Panay Hydro (GWh)": 20,
      "Panay Biomass (GWh)": 25,
      "Panay Solar (GWh)": 0,
      "Panay Wind (GWh)": 55,
      "Leyte-Samar Total Power Generation (GWh)": "3,900",
      "Leyte-Samar Total Non-Renewable (GWh)": 60,
      "Leyte-Samar Total Renewable (GWh)": "3,840",
      "Leyte-Samar Geothermal (GWh)": "3,820",
      "Leyte-Samar Hydro (GWh)": 0,
      "Leyte-Samar Biomass (GWh)": 0,
      "Leyte-Samar Solar (GWh)": 20,
      "Leyte-Samar Wind (GWh)": 0,
      "Bohol Total Power Generation (GWh)": 70,
      "Bohol Total Non-Renewable (GWh)": 66,
      "Bohol Total Renewable (GWh)": 4,
      "Bohol Geothermal (GWh)": 0,
      "Bohol Hydro (GWh)": 4,
      "Bohol Biomass (GWh)": 0,
      "Bohol Solar (GWh)": 0,
      "Bohol Wind (GWh)": 0,
      "Visayas Total Power Generation (GWh)": "14,560",
      "Visayas Total Power Consumption (GWh)": "13,950",
      "Solar Cost (PHP/W)": 85,
      "MERALCO Rate (PHP/kWh)": 10
    },
    {
      id: "67c698036bbacc4b3abdd2d3",
      Year: 2023,
      "Cebu Total Power Generation (GWh)": "6,300",
      "Cebu Total Non-Renewable Energy (GWh)": "6,150",
      "Cebu Total Renewable Energy (GWh)": 150,
      "Cebu Geothermal (GWh)": 0,
      "Cebu Hydro (GWh)": 3,
      "Cebu Biomass (GWh)": 2,
      "Cebu Solar (GWh)": 145,
      "Cebu Wind (GWh)": 0,
      "Negros Total Power Generation (GWh)": "2,750",
      "Negros Total Non-Renewable Energy (GWh)": 20,
      "Negros Total Renewable Energy (GWh)": "2,730",
      "Negros Geothermal (GWh)": "1,720",
      "Negros Hydro (GWh)": 8,
      "Negros Biomass (GWh)": 480,
      "Negros Solar (GWh)": 522,
      "Negros Wind (GWh)": 0,
      "Panay Total Power Generation (GWh)": "3,250",
      "Panay Total Non-Renewable Energy (GWh)": "1,480",
      "Panay Total Renewable Energy (GWh)": 770,
      "Panay Geothermal (GWh)": 0,
      "Panay Hydro (GWh)": 23,
      "Panay Biomass (GWh)": 62,
      "Panay Solar (GWh)": 15,
      "Panay Wind (GWh)": 670,
      "Leyte-Samar Total Power Generation (GWh)": "4,400",
      "Leyte-Samar Total Non-Renewable (GWh)": 35,
      "Leyte-Samar Total Renewable (GWh)": "4,365",
      "Leyte-Samar Geothermal (GWh)": "4,200",
      "Leyte-Samar Hydro (GWh)": 0,
      "Leyte-Samar Biomass (GWh)": 0,
      "Leyte-Samar Solar (GWh)": 165,
      "Leyte-Samar Wind (GWh)": 0,
      "Bohol Total Power Generation (GWh)": 95,
      "Bohol Total Non-Renewable (GWh)": 75,
      "Bohol Total Renewable (GWh)": 20,
      "Bohol Geothermal (GWh)": 0,
      "Bohol Hydro (GWh)": 12,
      "Bohol Biomass (GWh)": 0,
      "Bohol Solar (GWh)": 8,
      "Bohol Wind (GWh)": 0,
      "Visayas Total Power Generation (GWh)": "16,795",
      "Visayas Total Power Consumption (GWh)": "15,520",
      "Solar Cost (PHP/W)": 65,
      "MERALCO Rate (PHP/kWh)": 11.5
    }
  ];
  
  // Simplified table data for the data grid
  export const tableData = peerToPeerDummyData.map(item => ({
    id: item.id,
    year: item.Year,
    cebuTotal: item["Cebu Total Power Generation (GWh)"],
    negrosTotal: item["Negros Total Power Generation (GWh)"],
    panayTotal: item["Panay Total Power Generation (GWh)"],
    leyteSamarTotal: item["Leyte-Samar Total Power Generation (GWh)"],
    boholTotal: item["Bohol Total Power Generation (GWh)"],
    visayasTotal: item["Visayas Total Power Generation (GWh)"],
    cebuRenewable: item["Cebu Total Renewable Energy (GWh)"],
    negrosRenewable: item["Negros Total Renewable Energy (GWh)"],
    panayRenewable: item["Panay Total Renewable Energy (GWh)"],
    leyteSamarRenewable: item["Leyte-Samar Total Renewable (GWh)"],
    boholRenewable: item["Bohol Total Renewable (GWh)"]
  }));
  
  // Formatted chart data for different chart types
  export const chartData = {
    // Regional overview chart data
    regionalOverview: [
      { name: '2020', Cebu: 5500, Negros: 2310, Panay: 2780, 'Leyte-Samar': 3900, Bohol: 70 },
      { name: '2021', Cebu: 5890, Negros: 2520, Panay: 2980, 'Leyte-Samar': 4100, Bohol: 75 },
      { name: '2022', Cebu: 6145, Negros: 2638, Panay: 3105, 'Leyte-Samar': 4253, Bohol: 81 },
      { name: '2023', Cebu: 6300, Negros: 2750, Panay: 3250, 'Leyte-Samar': 4400, Bohol: 95 }
    ],
    
    // Renewable vs Non-Renewable chart data
    renewableVsNonRenewable: [
      { 
        name: 'Cebu', 
        Renewable: 150, 
        NonRenewable: 6150
      },
      { 
        name: 'Negros', 
        Renewable: 2730, 
        NonRenewable: 20
      },
      { 
        name: 'Panay', 
        Renewable: 770, 
        NonRenewable: 1480
      },
      { 
        name: 'Leyte-Samar', 
        Renewable: 4365, 
        NonRenewable: 35
      },
      { 
        name: 'Bohol', 
        Renewable: 20, 
        NonRenewable: 75
      }
    ],
    
    // Solar Distribution chart data
    solarDistribution: [
      { name: 'Cebu', Solar: 145 },
      { name: 'Negros', Solar: 522 },
      { name: 'Panay', Solar: 15 },
      { name: 'Leyte-Samar', Solar: 165 },
      { name: 'Bohol', Solar: 8 }
    ]
  };
  
  // Colors for charts
  export const chartColors = {
    regions: {
      Cebu: '#8884d8',
      Negros: '#82ca9d',
      Panay: '#ffc658',
      'Leyte-Samar': '#ff8042',
      Bohol: '#0088fe'
    },
    energyTypes: {
      Renewable: '#4caf50',
      NonRenewable: '#f44336',
      Solar: '#ffeb3b',
      Wind: '#2196f3',
      Hydro: '#03a9f4',
      Geothermal: '#ff9800',
      Biomass: '#8bc34a'
    }
  };