/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 alter.gltf 
Author: Alex Reeves (https://sketchfab.com/apreeves)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/renewable-alternative-energy-low-poly-943f1c168b4c47758ede9a961f523493
Title: Renewable & Alternative Energy - Low Poly
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/alter.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.4}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[-1515.07, 395.041, 2677.336]} scale={100}>
            <mesh geometry={nodes.biomass_base_material_0.geometry} material={materials.base_material} />
            <mesh geometry={nodes.biomass_base_material008_0.geometry} material={materials['base_material.008']} />
          </group>
          <group position={[-2309.993, 264.29, 1397.051]} rotation={[-Math.PI / 2, 0, 0]} scale={[25.213, 25.213, 74.226]}>
            <mesh geometry={nodes.biofuel_base_material013_0.geometry} material={materials['base_material.013']} />
            <mesh geometry={nodes.biofuel_base_material_0.geometry} material={materials.base_material} />
            <mesh geometry={nodes.biofuel_base_material009_0.geometry} material={materials['base_material.009']} />
            <mesh geometry={nodes.biofuel_base_material010_0.geometry} material={materials['base_material.010']} />
            <mesh geometry={nodes.biofuel_base_material011_0.geometry} material={materials['base_material.011']} />
            <mesh geometry={nodes.biofuel_base_material012_0.geometry} material={materials['base_material.012']} />
            <mesh geometry={nodes.biofuel_base_material014_0.geometry} material={materials['base_material.014']} />
            <mesh geometry={nodes.biofuel_base_material015_0.geometry} material={materials['base_material.015']} />
            <mesh geometry={nodes.biofuel_base_material016_0.geometry} material={materials['base_material.016']} />
            <mesh geometry={nodes.biofuel_base_material017_0.geometry} material={materials['base_material.017']} />
            <mesh geometry={nodes.biofuel_base_material019_0.geometry} material={materials['base_material.019']} />
            <mesh geometry={nodes.biofuel_base_material020_0.geometry} material={materials['base_material.020']} />
            <mesh geometry={nodes.biofuel_base_material021_0.geometry} material={materials['base_material.021']} />
            <mesh geometry={nodes.biofuel_base_material022_0.geometry} material={materials['base_material.022']} />
            <mesh geometry={nodes.biofuel_base_material023_0.geometry} material={materials['base_material.023']} />
          </group>
          <mesh geometry={nodes.solarpanels_base_material_0.geometry} material={materials.base_material} position={[1083.595, 209.903, 86.832]} rotation={[-2.045, 0, 0]} scale={140.841} />
          <mesh geometry={nodes.windmill_base_base_material_0.geometry} material={materials.base_material} position={[11.097, 425.557, 1424.254]} rotation={[-Math.PI / 2, 0, 0]} scale={43.934} />
          <mesh geometry={nodes.windmill_blades_base_material_0.geometry} material={materials.base_material} position={[9.984, 620.761, 1305.94]} rotation={[Math.PI / 2, -Math.PI / 3, Math.PI]} scale={[139.246, 238.273, 139.246]} />
          <mesh geometry={nodes.hydroelectric_dam_base_material_0.geometry} material={materials.base_material} position={[-1030.373, 95.963, 272.389]} rotation={[-Math.PI / 2, 0, 0]} scale={89.063} />
          <mesh geometry={nodes.hydroelectric_lightning_base_material_0.geometry} material={materials.base_material} position={[-1469.959, 358.107, 39.346]} rotation={[-Math.PI / 2, -0.256, -Math.PI / 2]} scale={70.243} />
          <mesh geometry={nodes.hydrogen_base_material_0.geometry} material={materials.base_material} position={[1195.086, 364.547, 3105.96]} scale={100} />
          <mesh geometry={nodes.biomass_logo_base_material_0.geometry} material={materials.base_material} position={[-899.747, 148.187, 2479.879]} rotation={[Math.PI, 0, Math.PI]} scale={63.989} />
          <mesh geometry={nodes.geothermal_base_material_0.geometry} material={materials.base_material} position={[1926.944, -241.552, 1472.699]} scale={71.391} />
          <mesh geometry={nodes.Plane__0.geometry} material={materials.Plane__0} position={[8.591, 2.074, 1408.53]} rotation={[-Math.PI / 2, 0, 0]} scale={497.154} />
          <mesh geometry={nodes.Plane002__0.geometry} material={materials.Plane__0} position={[2153.107, 2.074, 1408.53]} rotation={[-Math.PI / 2, 0, 0]} scale={708.736} />
          <mesh geometry={nodes.Plane003__0.geometry} material={materials.Plane__0} position={[987.928, 2.074, 3086.833]} rotation={[-Math.PI / 2, 0, 0]} scale={787.606} />
          <mesh geometry={nodes.Plane004__0.geometry} material={materials.Plane__0} position={[-1250.421, 2.074, 2853.426]} rotation={[-Math.PI / 2, 0, 0]} scale={787.606} />
          <mesh geometry={nodes.Plane005__0.geometry} material={materials.Plane__0} position={[-2166.523, 2.074, 1482.458]} rotation={[-Math.PI / 2, 0, 0]} scale={591.474} />
          <mesh geometry={nodes.Plane006__0.geometry} material={materials.Plane__0} position={[-1149.745, 2.074, 99.412]} rotation={[-Math.PI / 2, 0, 0]} scale={694.609} />
          <mesh geometry={nodes.Plane007__0.geometry} material={materials.Plane__0} position={[1058.725, 2.074, 99.412]} rotation={[-Math.PI / 2, 0, 0]} scale={694.609} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/alter.gltf')
